services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - authservice
      - chatservice
    environment:
      - REACT_APP_CHAT_URL=http://localhost:80
      - REACT_APP_AUTH_URL=http://localhost:81

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: ${SQLSERVER_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "2867:1433"
    volumes:
      - ./sqlserver:/var/opt/mssql/data
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - ./redis:/data
    env_file:
      - .env  

  chatservice:
    build: ./chatservice
    depends_on:
      - sqlserver
      - redis
    ports:
      - "80:8080"
    env_file:
      - .env

  authservice:
    build: ./authservice
    depends_on:
      - sqlserver
    ports:
      - "81:8080"
    env_file:
      - .env

volumes:
  sqlserver:
  redis:
